# SPDX-FileCopyrightText: 2021 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: No License selected

stages:
  - setup
  - test

setup:
  image: python:3.9
  stage: setup
  script:
    - pip install -r requirements.txt
    - cd gitcalendar_webservice
    - cp gitcalendar_webservice/private_settings.py.example gitcalendar_webservice/private_settings.py
    - python manage.py migrate
  tags:
    - docker

tests:
  image: python:3.9
  stage: test
  script:
    - pip install -r requirements.txt
    - cd gitcalendar_webservice
    - cp gitcalendar_webservice/private_settings.py.example gitcalendar_webservice/private_settings.py
    - python manage.py test
  tags:
    - docker
